power: reset: rename s2mpg10.h -> s2mpg10-local.h
The core s2mpg10 driver was upstreamed in commit 5338709089b7 ("mfd:
sec: Add support for S2MPG10 PMIC"), see [1]. This causes several name
collisions with the downstream version since it shares the same header
file 's2mpg10.h', e.g.:

  include/linux/mfd/samsung/s2mpg10-register.h:20:2: error: redefinition of enumerator 'S2MPG10_COMMON_CHIPID'
   20 |         S2MPG10_COMMON_CHIPID = 0x0,
      |         ^

To resolve these build issues, rename the downstream header to
's2mpg10-local.h'. This serves as a temporary workaround while the
codebase switches to use the upstream version of the driver.

Bug: 429859675
Cc: André Draszik <draszik@google.com>
Link: https://git.kernel.org/torvalds/c/5338709089b7 [1]
Change-Id: I5b8900f765552a97b13357153470f7847a743c51
Signed-off-by: Carlos Llamas <cmllamas@google.com>